services:
  db-gerenciado-master:
    image: mysql:8.0
    container_name: db-gerenciado-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=aula-db
    volumes:
      - master_data:/var/lib/mysql

  db-gerenciado-slave:
    image: mysql:8.0
    container_name: db-gerenciado-slave
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --server-id=2 --relay-log=relay-bin --log-bin=mysql-bin --binlog-do-db=aula-db
    depends_on:
      - db-gerenciado-master
    volumes:
      - slave_data:/var/lib/mysql

volumes:
  master_data:
  slave_data: